services:
  - type: web
    name: Jester
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - fromGroup: database-credentials
      - key: DB_SSL_CA
        value: /etc/secrets/ca.pem
    secretFiles:
      - name: ca.pem
        mountPath: /etc/secrets/ca.pem

databases:
  - name: MySQL
    databaseName: ${{MySQL.MYSQLDATABASE}}
    user: ${{MySQL.MYSQLUSER}}
    plan: free